### ISSUE TITLE
Agregar imagenes a las tecnologías en phpmexico.mx

### ISSUE THREAD

**Issue by dmouse** [phpmx/phpmexico#18]
A muchas de las tecnologías les falta su logo https://phpmexico.mx

**Comment by javleds** [comment]
Qué opinas de utilizar temporalmente el logo de phpméxico para llenar esas tecnologías mientras conseguimos los logos?
Si gustas se puede realizar con un Query y/o migración.

Inclusive podríamos agregar una animación sutil (con hover) sobre las tarjetas y centrar el texto (opcional). Si estás de acuerdo, podría gestionar esto en otro issue.

**Comment by javleds** [comment]
![logos](https://user-images.githubusercontent.com/11241239/85090247-4184cb80-b1aa-11ea-8b91-b514a6ed28f9.gif)
Ejemplificando la idea del comentario aterior.

**Comment by jashk** [comment]
Creo que este PR #27 resuelve el problema con las imágenes rotas, pero aun así es necesario actualizar las que corresponden desde /admin
