### ISSUE TITLE
Bloque de Meetup: 

### ISSUE THREAD

**Issue by dmouse** [phpmx/phpmexico#38]
Relacionado: #37 

Como parte del home page hay que extraer el próximo evento en meetup, en caso de que no haya un evento próximo debe traer el último evento que haya pasado

**Comment by javleds** [comment]
Alguien está trabajando en esto?

**Comment by gueroverde** [comment]
> Alguien está trabajando en esto?

Ahora estas asignado ^^

**Comment by javleds** [comment]
Hay un PR en curso que sirve para cubrir este punto: https://github.com/phpmx/phpmexico/pull/46
