### ISSUE TITLE
Crer diseño de página por evento

### ISSUE THREAD

**Issue by dmouse** [phpmx/phpmexico#39]
Relacionado: #37 

Para crear una página interior de eventos y tener los ultimos eventos, necesitamos crear una entidad donde podramos almacenar los datos de cada evento que esta en meetup para después solo hacer un query y tener los datos listos.

las charlas debe poder ser accesibles via /`charla/nombre-bonito-de-la-charla` #55

**Comment by javleds** [comment]
Actualmente el pull request https://github.com/phpmx/phpmexico/pull/46 crea una entidad para almacenar datos de los eventos, se podría agregar la funcionalidad correspondiente para consultar la información obtenida y guardada en la base de datos.

> Nota: El PR no soluciona este isue, pero puede ayudar a resolverlo.
