### ISSUE TITLE
Crear un comando para que actualizar los eventos de meetup

### ISSUE THREAD

**Issue by dmouse** [phpmx/phpmexico#40]
Relacionado: #37 

Para poder actualizar los eventos de manera automatica necesitamos un comando que se ejecute con cron para sincronizar los eventos con nuestro sitio.

**Comment by javleds** [comment]
Ya se tiene un PR para esto: https://github.com/phpmx/phpmexico/pull/46

De igual manera, si el comando llegar a a fallar, existe otro issue relacionado https://github.com/phpmx/phpmexico/issues/55, cuya finalidad es crear un formulario para cargarlos manualmente y/o agregar información faltante.
