### ISSUE TITLE
Crear formulario de registro del meetup en EasyAdmin

### ISSUE THREAD

**Issue by dmouse** [phpmx/phpmexico#55]
El meetup debe tener

* Link a meetup
* Link a youtube  ( para poder generar el embed #54)
* Link de redes sociales para seguir la charla
* Link del speaker
* Link a las slides
* Descripcion de la charla
* Image para las redes sociales, solo disponible via metadata

**Comment by javleds** [comment]
PR relacionado: https://github.com/phpmx/phpmexico/pull/71
