### ISSUE TITLE
Crear el formulario en EasyAdmin para dar de alta a empresas que patrocinan a la comunidad

### ISSUE THREAD

**Issue by dmouse** [phpmx/phpmexico#56]
En el formulario se debe poder registrar empresas, subir su logo, link y nombre

**Comment by javleds** [comment]
@dmouse este formulario será publico o se debe agregar a EasyAdmin?

**Comment by dmouse** [comment]
El formulario debe ser privado accesible desde easyadmin

**Comment by javleds** [comment]
@dmouse @jcarlosjl 

El PR https://github.com/phpmx/phpmexico/pull/65 soluciona éste issue, cierto?

**Comment by javleds** [comment]
Issue resuelto con PR https://github.com/phpmx/phpmexico/pull/65
